// const countryList = {
//   AED: { code: "AE", country: "United Arab Emirates" },
//   AFN: { code: "AF", country: "Afghanistan" },
//   XCD: { code: "AG", country: "Antigua and Barbuda" },
//   ALL: { code: "AL", country: "Albania" },
//   AMD: { code: "AM", country: "Armenia" },
//   ANG: { code: "AN", country: "Netherlands Antilles" },
//   AOA: { code: "AO", country: "Angola" },
//   AQD: { code: "AQ", country: "Antarctica" },
//   ARS: { code: "AR", country: "Argentina" },
//   AUD: { code: "AU", country: "Australia" },
//   AZN: { code: "AZ", country: "Azerbaijan" },
//   BAM: { code: "BA", country: "Bosnia and Herzegovina" },
//   BBD: { code: "BB", country: "Barbados" },
//   BDT: { code: "BD", country: "Bangladesh" },
//   XOF: { code: "BE", country: "Belgium" },
//   BGN: { code: "BG", country: "Bulgaria" },
//   BHD: { code: "BH", country: "Bahrain" },
//   BIF: { code: "BI", country: "Burundi" },
//   BMD: { code: "BM", country: "Bermuda" },
//   BND: { code: "BN", country: "Brunei" },
//   BOB: { code: "BO", country: "Bolivia" },
//   BRL: { code: "BR", country: "Brazil" },
//   BSD: { code: "BS", country: "Bahamas" },
//   NOK: { code: "BV", country: "Norway" },
//   BWP: { code: "BW", country: "Botswana" },
//   BYR: { code: "BY", country: "Belarus" },
//   BZD: { code: "BZ", country: "Belize" },
//   CAD: { code: "CA", country: "Canada" },
//   CDF: { code: "CD", country: "Congo" },
//   XAF: { code: "CF", country: "Central African Republic" },
//   CHF: { code: "CH", country: "Switzerland" },
//   CLP: { code: "CL", country: "Chile" },
//   CNY: { code: "CN", country: "China" },
//   COP: { code: "CO", country: "Colombia" },
//   CRC: { code: "CR", country: "Costa Rica" },
//   CUP: { code: "CU", country: "Cuba" },
//   CVE: { code: "CV", country: "Cape Verde" },
//   CYP: { code: "CY", country: "Cyprus" },
//   CZK: { code: "CZ", country: "Czech Republic" },
//   DJF: { code: "DJ", country: "Djibouti" },
//   DKK: { code: "DK", country: "Denmark" },
//   DOP: { code: "DO", country: "Dominican Republic" },
//   DZD: { code: "DZ", country: "Algeria" },
//   ECS: { code: "EC", country: "Ecuador" },
//   EEK: { code: "EE", country: "Estonia" },
//   EGP: { code: "EG", country: "Egypt" },
//   ETB: { code: "ET", country: "Ethiopia" },
//   EUR: { code: "FR", country: "France" },
//   FJD: { code: "FJ", country: "Fiji" },
//   FKP: { code: "FK", country: "Falkland Islands" },
//   GBP: { code: "GB", country: "United Kingdom" },
//   GEL: { code: "GE", country: "Georgia" },
//   GGP: { code: "GG", country: "Guernsey" },
//   GHS: { code: "GH", country: "Ghana" },
//   GIP: { code: "GI", country: "Gibraltar" },
//   GMD: { code: "GM", country: "Gambia" },
//   GNF: { code: "GN", country: "Guinea" },
//   GTQ: { code: "GT", country: "Guatemala" },
//   GYD: { code: "GY", country: "Guyana" },
//   HKD: { code: "HK", country: "Hong Kong" },
//   HNL: { code: "HN", country: "Honduras" },
//   HRK: { code: "HR", country: "Croatia" },
//   HTG: { code: "HT", country: "Haiti" },
//   HUF: { code: "HU", country: "Hungary" },
//   IDR: { code: "ID", country: "Indonesia" },
//   ILS: { code: "IL", country: "Israel" },
//   INR: { code: "IN", country: "India" },
//   IQD: { code: "IQ", country: "Iraq" },
//   IRR: { code: "IR", country: "Iran" },
//   ISK: { code: "IS", country: "Iceland" },
//   JMD: { code: "JM", country: "Jamaica" },
//   JOD: { code: "JO", country: "Jordan" },
//   JPY: { code: "JP", country: "Japan" },
//   KES: { code: "KE", country: "Kenya" },
//   KGS: { code: "KG", country: "Kyrgyzstan" },
//   KHR: { code: "KH", country: "Cambodia" },
//   KMF: { code: "KM", country: "Comoros" },
//   KPW: { code: "KP", country: "North Korea" },
//   KRW: { code: "KR", country: "South Korea" },
//   KWD: { code: "KW", country: "Kuwait" },
//   KYD: { code: "KY", country: "Cayman Islands" },
//   KZT: { code: "KZ", country: "Kazakhstan" },
//   LAK: { code: "LA", country: "Laos" },
//   LBP: { code: "LB", country: "Lebanon" },
//   LKR: { code: "LK", country: "Sri Lanka" },
//   LRD: { code: "LR", country: "Liberia" },
//   LSL: { code: "LS", country: "Lesotho" },
//   LTL: { code: "LT", country: "Lithuania" },
//   LVL: { code: "LV", country: "Latvia" },
//   LYD: { code: "LY", country: "Libya" },
//   MAD: { code: "MA", country: "Morocco" },
//   MDL: { code: "MD", country: "Moldova" },
//   MGA: { code: "MG", country: "Madagascar" },
//   MKD: { code: "MK", country: "North Macedonia" },
//   MMK: { code: "MM", country: "Myanmar" },
//   MNT: { code: "MN", country: "Mongolia" },
//   MOP: { code: "MO", country: "Macau" },
//   MRO: { code: "MR", country: "Mauritania" },
//   MTL: { code: "MT", country: "Malta" },
//   MUR: { code: "MU", country: "Mauritius" },
//   MVR: { code: "MV", country: "Maldives" },
//   MWK: { code: "MW", country: "Malawi" },
//   MXN: { code: "MX", country: "Mexico" },
//   MYR: { code: "MY", country: "Malaysia" },
//   MZN: { code: "MZ", country: "Mozambique" },
//   NAD: { code: "NA", country: "Namibia" },
//   XPF: { code: "NC", country: "New Caledonia" },
//   NGN: { code: "NG", country: "Nigeria" },
//   NIO: { code: "NI", country: "Nicaragua" },
//   NPR: { code: "NP", country: "Nepal" },
//   NZD: { code: "NZ", country: "New Zealand" },
//   OMR: { code: "OM", country: "Oman" },
//   PAB: { code: "PA", country: "Panama" },
//   PEN: { code: "PE", country: "Peru" },
//   PGK: { code: "PG", country: "Papua New Guinea" },
//   PHP: { code: "PH", country: "Philippines" },
//   PKR: { code: "PK", country: "Pakistan" },
//   PLN: { code: "PL", country: "Poland" },
//   PYG: { code: "PY", country: "Paraguay" },
//   QAR: { code: "QA", country: "Qatar" },
//   RON: { code: "RO", country: "Romania" },
//   RSD: { code: "RS", country: "Serbia" },
//   RUB: { code: "RU", country: "Russia" },
//   RWF: { code: "RW", country: "Rwanda" },
//   SAR: { code: "SA", country: "Saudi Arabia" },
//   SBD: { code: "SB", country: "Solomon Islands" },
//   SCR: { code: "SC", country: "Seychelles" },
//   SDG: { code: "SD", country: "Sudan" },
//   SEK: { code: "SE", country: "Sweden" },
//   SGD: { code: "SG", country: "Singapore" },
//   SKK: { code: "SK", country: "Slovakia" },
//   SLL: { code: "SL", country: "Sierra Leone" },
//   SOS: { code: "SO", country: "Somalia" },
//   SRD: { code: "SR", country: "Suriname" },
//   STD: { code: "ST", country: "Sao Tome and Principe" },
//   SVC: { code: "SV", country: "El Salvador" },
//   SYP: { code: "SY", country: "Syria" },
//   SZL: { code: "SZ", country: "Eswatini" },
//   THB: { code: "TH", country: "Thailand" },
//   TJS: { code: "TJ", country: "Tajikistan" },
//   TMT: { code: "TM", country: "Turkmenistan" },
//   TND: { code: "TN", country: "Tunisia" },
//   TOP: { code: "TO", country: "Tonga" },
//   TRY: { code: "TR", country: "Turkey" },
//   TTD: { code: "TT", country: "Trinidad and Tobago" },
//   TWD: { code: "TW", country: "Taiwan" },
//   TZS: { code: "TZ", country: "Tanzania" },
//   UAH: { code: "UA", country: "Ukraine" },
//   UGX: { code: "UG", country: "Uganda" },
//   USD: { code: "US", country: "United States" },
//   UYU: { code: "UY", country: "Uruguay" },
//   UZS: { code: "UZ", country: "Uzbekistan" },
//   VEF: { code: "VE", country: "Venezuela" },
//   VND: { code: "VN", country: "Vietnam" },
//   VUV: { code: "VU", country: "Vanuatu" },
//   YER: { code: "YE", country: "Yemen" },
//   ZAR: { code: "ZA", country: "South Africa" },
//   ZMK: { code: "ZM", country: "Zambia" },
//   ZWD: { code: "ZW", country: "Zimbabwe" },
// };
